print("\n📱 CALCULATOR MENU:")
print("1. Basic Math (+, -, *, /)")
print("2. Power & Root")
print("3. Temperature Converter")
print("4. Tip Calculator")
print("5. BMI Calculator")
print("6. Grade Calculator")
print("0. Exit")
print("-"*50)
choice = input("\nSelect operation (0-6): ").strip()
valid_choices = ["0", "1", "2", "3", "4", "5", "6"]
print("❌ Invalid choice! Please select 0-6")
print("👋 Thank you for using our calculator. Goodbye!")
print("\n--- BASIC MATH OPERATIONS ---")
print("Operations: + (add), - (subtract), * (multiply), / (divide)")
num1_str = input("Enter first number: ")
num2_str = input("Enter second number: ")
operation = input("Enter operation (+, -, *, /): ").strip()
print("❌ First number is invalid!")
print("❌ Second number is invalid!")
